title: Co-MASK
Email: co.mask.community@gmail.com
description: DIY fabric masks for preserving our humanity through hope, humor, and hygiene!
theme: jekyll-theme-minimal
logo: logo.jpg
github:
  is_project_page: true
